apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookreader

resources:
- ../../base
- ingress.yaml

images:
- name: app
  newName: ghcr.io/jaennil/bookreader2/app
  newTag: e6ff9f3e84f2fff04c66cdcfacadc15385b50d2c
