apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookreader

resources:
- ../../base
- ingress.yaml

images:
- name: app
  newName: ghcr.io/jaennil/bookreader2/app
  newTag: f7ca17880e6a0b9983cae5e6a917ac123607c771
