apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookreader

resources:
- ../../base
- ingress.yaml

images:
- name: app
  newName: ghcr.io/jaennil/bookreader2/app
  newTag: 34628880db5b46bd37f7eac7998a4c3849a8cfc3
